# Pandas: concat(), merge() y join()

Este notebook está diseñado para ejecutar cada celda y observar cómo funcionan las principales técnicas para combinar información en Pandas.

In [1]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)

Pandas version: 2.3.3

## 1. Concatenación vertical con concat()

In [2]:
enero = pd.DataFrame({
    'producto':['Laptop','Mouse'],
    'ventas':[10,25]
})

febrero = pd.DataFrame({
    'producto':['Teclado','Monitor'],
    'ventas':[15,8]
})

resultado = pd.concat([enero, febrero])
resultado

  producto  ventas
0   Laptop      10
1    Mouse      25
0  Teclado      15
1  Monitor       8

### Corregir índices con ignore_index

In [3]:
resultado = pd.concat(
    [enero, febrero],
    ignore_index=True
)
resultado

  producto  ventas
0   Laptop      10
1    Mouse      25
2  Teclado      15
3  Monitor       8

## 2. Concatenación horizontal

In [4]:
clientes = pd.DataFrame({
    'nombre':['Juan','Ana']
})

compras = pd.DataFrame({
    'total':[500,300]
})

pd.concat([clientes, compras], axis=1)

  nombre  total
0   Juan    500
1    Ana    300

## 3. Outer Join usando concat

In [5]:
df1 = pd.DataFrame({'A':[1,2]}, index=[0,1])
df2 = pd.DataFrame({'B':[10,20]}, index=[1,2])

pd.concat([df1, df2], axis=1)

     A     B
0  1.0   NaN
1  2.0  10.0
2  NaN  20.0

## 4. Inner Join usando concat

In [6]:
pd.concat(
    [df1, df2],
    axis=1,
    join='inner'
)

   A   B
1  2  10

## 5. Left y Right Join con reindex

In [7]:
left_join = pd.concat([df1, df2], axis=1).reindex(df1.index)
right_join = pd.concat([df1, df2], axis=1).reindex(df2.index)

print("LEFT JOIN")
display(left_join)

print("RIGHT JOIN")
display(right_join)

LEFT JOIN

     A     B
0  1.0   NaN
1  2.0  10.0

RIGHT JOIN

     A     B
1  2.0  10.0
2  NaN  20.0

## 6. merge() básico

In [8]:
clientes = pd.DataFrame({
    'id':[1,2,3],
    'nombre':['Juan','Ana','Pedro']
})

ventas = pd.DataFrame({
    'id':[1,2,3],
    'monto':[500,300,700]
})

pd.merge(clientes, ventas, on='id')

   id nombre  monto
0   1   Juan    500
1   2    Ana    300
2   3  Pedro    700

## 7. merge() con múltiples llaves

In [9]:
ventas = pd.DataFrame({
    'cliente':[1,1,2],
    'mes':['Enero','Febrero','Enero'],
    'venta':[100,200,300]
})

pagos = pd.DataFrame({
    'cliente':[1,1,2],
    'mes':['Enero','Febrero','Enero'],
    'pagado':[True,False,True]
})

pd.merge(
    ventas,
    pagos,
    on=['cliente','mes']
)

   cliente      mes  venta  pagado
0        1    Enero    100    True
1        1  Febrero    200   False
2        2    Enero    300    True

## 8. Diferentes valores de how

In [10]:
left = pd.DataFrame({
    'id':[1,2,3],
    'nombre':['Juan','Ana','Pedro']
})

right = pd.DataFrame({
    'id':[2,3,4],
    'ciudad':['CDMX','Monterrey','Guadalajara']
})

print("INNER")
display(pd.merge(left,right,on='id',how='inner'))

print("LEFT")
display(pd.merge(left,right,on='id',how='left'))

print("RIGHT")
display(pd.merge(left,right,on='id',how='right'))

print("OUTER")
display(pd.merge(left,right,on='id',how='outer'))

INNER

   id nombre     ciudad
0   2    Ana       CDMX
1   3  Pedro  Monterrey

LEFT

   id nombre     ciudad
0   1   Juan        NaN
1   2    Ana       CDMX
2   3  Pedro  Monterrey

RIGHT

   id nombre       ciudad
0   2    Ana         CDMX
1   3  Pedro    Monterrey
2   4    NaN  Guadalajara

OUTER

   id nombre       ciudad
0   1   Juan          NaN
1   2    Ana         CDMX
2   3  Pedro    Monterrey
3   4    NaN  Guadalajara

## 9. CROSS JOIN (producto cartesiano)

In [11]:
clientes = pd.DataFrame({
    'cliente':['Juan','Ana']
})

productos = pd.DataFrame({
    'producto':['Laptop','Mouse']
})

pd.merge(
    clientes,
    productos,
    how='cross'
)

  cliente producto
0    Juan   Laptop
1    Juan    Mouse
2     Ana   Laptop
3     Ana    Mouse

## 10. join() usando índices

In [12]:
clientes = pd.DataFrame(
    {'nombre':['Juan','Ana']},
    index=[1,2]
)

ventas = pd.DataFrame(
    {'monto':[500,300]},
    index=[1,2]
)

clientes.join(ventas)

  nombre  monto
1   Juan    500
2    Ana    300

## 11. join() usando una columna

In [13]:
df = pd.DataFrame({
    'id':[1,2,3],
    'nombre':['Juan','Ana','Pedro']
})

other = pd.DataFrame({
    'id':[1,2,3],
    'monto':[500,300,700]
})

df.join(
    other.set_index('id'),
    on='id'
)

   id nombre  monto
0   1   Juan    500
1   2    Ana    300
2   3  Pedro    700

# Ejercicio final

Intenta crear:

1. Un DataFrame de empleados.
2. Un DataFrame de departamentos.
3. Relaciónalos usando merge().
4. Prueba inner, left, right y outer.
5. Agrega una tercera tabla y utiliza concat().

In [30]:
empleados = pd.DataFrame({
    'id':[1,2,3,4,5],
    'nombre':['Juan','Ana','Pedro','Diego','Maria'],
    'departamento_id':[1,5,9,10,6]
})

departamento = pd.DataFrame({
    'departamento_id':[5,1,9,10],
    'nombre_dep':['Ventas','Marketing','Recursos Humanos','Ingenieria'],
    'ubicacion':['CDMX','Monterrey','Guadalajara','Puebla']
})

resultado = pd.merge(empleados, departamento, on='departamento_id', how='inner')
print(resultado)

emplydep = pd.DataFrame({
    'id':[1],
    'nombre':['Momol'],
    'departamento_id':[8],
    'nombre_dep':['Fuel'],
    'ubicacion':['CDMX']
})

resultado = pd.concat([resultado, emplydep], ignore_index=True)
print(resultado)

   id nombre  departamento_id        nombre_dep    ubicacion
0   1   Juan                1         Marketing    Monterrey
1   2    Ana                5            Ventas         CDMX
2   3  Pedro                9  Recursos Humanos  Guadalajara
3   4  Diego               10        Ingenieria       Puebla
   id nombre  departamento_id        nombre_dep    ubicacion
0   1   Juan                1         Marketing    Monterrey
1   2    Ana                5            Ventas         CDMX
2   3  Pedro                9  Recursos Humanos  Guadalajara
3   4  Diego               10        Ingenieria       Puebla
4   1  Momol                8              Fuel         CDMX