# Notebook 01 - PDFs en Python y Extracción de Tablas

Basado en la introducción al trabajo con PDFs y la lección de Tabula.

## Introducción
Los PDFs son una de las fuentes de información más comunes en Data Science. El objetivo es convertir texto, tablas e imágenes en estructuras analizables.

## Librerías importantes
- PyPDF
- PyMuPDF
- pdfplumber
- tabula-py
- OCR (Tesseract)

In [ ]:
import pandas as pd
import pypdf
from pypdf import PdfReader

%JAVA_HOME%
C:\Program Files (x86)\Common Files\Oracle\Java\java8path\java.exe

# Leer PDF

In [19]:
reader = PdfReader("4. sample.pdf")

In [21]:
page = reader.pages[0]
print(page.extract_text())

Sample PDFThis is a simple PDF ﬁle. Fun fun fun.
Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus facilisis odio sed mi.
Curabitur suscipit. Nullam vel nisi. Etiam semper ipsum ut lectus. Proin aliquam, erat eget
pharetra commodo, eros mi condimentum quam, sed commodo justo quam ut velit.
Integer a erat. Cras laoreet ligula cursus enim. Aenean scelerisque velit et tellus.
Vestibulum dictum aliquet sem. Nulla facilisi. Vestibulum accumsan ante vitae elit. Nulla
erat dolor, blandit in, rutrum quis, semper pulvinar, enim. Nullam varius congue risus.
Vivamus sollicitudin, metus ut interdum eleifend, nisi tellus pellentesque elit, tristique
accumsan eros quam et risus. Suspendisse libero odio, mattis sit amet, aliquet eget,
hendrerit vel, nulla. Sed vitae augue. Aliquam erat volutpat. Aliquam feugiat vulputate nisl.
Suspendisse quis nulla pretium ante pretium mollis. Proin velit ligula, sagittis at, egestas a,
pulvinar quis, nisl.
Pellentesque sit amet lectus. Praesent pulvinar, nunc quis iaculis sagittis, justo quam
lobortis tortor, sed vestibulum dui metus venenatis est. Nunc cursus ligula. Nulla facilisi.
Phasellus ullamcorper consectetuer ante. Duis tincidunt, urna id condimentum luctus, nibh
ante vulputate sapien, id sagittis massa orci ut enim. Pellentesque vestibulum convallis
sem. Nulla consequat quam ut nisl. Nullam est. Curabitur tincidunt dapibus lorem. Proin
velit turpis, scelerisque sit amet, iaculis nec, rhoncus ac, ipsum. Phasellus lorem arcu,
feugiat eu, gravida eu, consequat molestie, ipsum. Nullam vel est ut ipsum volutpat
feugiat. Aenean pellentesque.
In mauris. Pellentesque dui nisi, iaculis eu, rhoncus in, venenatis ac, ante. Ut odio justo,
scelerisque vel, facilisis non, commodo a, pede. Cras nec massa sit amet tortor volutpat
varius. Donec lacinia, neque a luctus aliquet, pede massa imperdiet ante, at varius lorem
pede sed sapien. Fusce erat nibh, aliquet in, eleifend eget, commodo eget, erat. Fusce
consectetuer. Cras risus tortor, porttitor nec, tristique sed, convallis semper, eros. Fusce
vulputate ipsum a mauris. Phasellus mollis. Curabitur sed urna. Aliquam nec sapien non
nibh pulvinar convallis. Vivamus facilisis augue quis quam. Proin cursus aliquet metus.
Suspendisse lacinia. Nulla at tellus ac turpis eleifend scelerisque. Maecenas a pede vitae
enim commodo interdum. Donec odio. Sed sollicitudin dui vitae justo.
Morbi elit nunc, facilisis a, mollis a, molestie at, lectus. Suspendisse eget mauris eu tellus
molestie cursus. Duis ut magna at justo dignissim condimentum. Cum sociis natoque
penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus varius. Ut sit
amet diam suscipit mauris ornare aliquam. Sed varius. Duis arcu. Etiam tristique massa
eget dui. Phasellus congue. Aenean est erat, tincidunt eget, venenatis quis, commodo at,
quam.

# Ficha tecnica Automovil

In [22]:
reader = PdfReader("4. SampleAudi.pdf")
page = reader.pages[0]
print(page.extract_text())

Ignoring wrong pointing object 12 0 (offset 0)
Ignoring wrong pointing object 46 0 (offset 0)

Ficha técnica
A1 Sportback 2024
        Motorización A1 SB 35 TFSI Ego A1 SB 40 TFSI  S line
Cilindrada 1.5 L (1,498 cm3)2.0 L  (1,984 cm3)
Motor 4 cil. en línea, TFSI4 cil. en línea, TFSI
Potencia 150 hp / 5,000- 6,000 rpm200 hp / 4,400-6,000 rpm
Torque 250 Nm / 1,500 -3,500 rpm320 Nm/1,500 - 4,400 rpm
Tracción delantera delantera
Transmisión S tronic 7 Vel.S tronic 6 Vel.
Velocidad máxima 222 km/ hr 235km/hr
Aceleración 0-100 km/hr 7.7 s 6.5 s
Rendimiento de combustible (ciudad / carretera / combinado)14.8/ 20.6/ 16.9  km/l13.7/ 19.4/ 15.8  km/l
Norma de emisión de gases EU6 EU6
Emisiones de CO₂ (ciudad / carretera / combinado) 159.1/ 114.0/ 138.8 gCO₂/km171.2/ 121.2/ 148.7 gCO₂/km
       DimensionesLargo 4029 mm 4029 mm
Ancho 1740 mm 1740 mm
Alto 1433 mm 1433 mm
Distancia entre ejes 2563 mm 2563 mm
Peso en vacío (con conductor) 1,240 kg 1,335 kg
Capacidad del maletero 335 l 335 l
Capacidad del tanque de combustible 40 l 40 l
Número de puertas 5 5
       Sistemas de Asistencia y Seguridad
Airbags delanteros con interruptor para desconectar el airbag del acompañanteS S
Airbags laterales delanteros con airbag de cabeza S S
Alarma antirrobo S S
Anclaje de fijación para asientos de niños para asientos traseros exterioresS S
Asistente de arranque en pendientes (Audi Hold Assist)S S
Asistente de estacionamiento trasero (sensores traseros)S -
Asistente de estacionamiento plus (sensores delanteros y traseros)O S
Cámara de reversa O O
Audi Park Assist O O
Audi Drive Select S S
Birlos de seguridad S S
Triángulo de seguridad S S
Cruise control y limitador de velocidad S S
Dirección asistida electromecánica S S
Frenos delanteros de disco S S
Frenos traseros de disco S S
S
S
S
S
A1 SB 30 TFSI Cool
S
S
S
S
S
149.2 / 105.1/ 129.4 gCO₂/km
1740 mm
1,200 kg
335 l
40 l
5
S
O
O
O
O
O
S
9.4 s
200 Nm / 2,000 - 3,500 rpm
delantera
1433mm
2563 mm
4029 mm
15.7/ 22.3/ 18.1 km/l
EU6
1.0 L  (999 cm3)
 3 cil. en línea, TFSI
116 hp / 5,000 -5,500 rpm
S tronic 7 Vel.
203 km/hr
A1

# Ahora con PyMuPDF

In [30]:
# !pip install PyMuPDF
import pymupdf
doc = pymupdf.open("4. SampleAudi.pdf")
page = doc.load_page(0)
print(page.get_text())

Ficha técnica
A1 Sportback 2024
        Motorización
A1 SB 35 TFSI
Ego
A1 SB 40 TFSI
S line
Cilindrada
1.5 L (1,498 cm3)
2.0 L  (1,984 cm3)
Motor
4 cil. en línea, TFSI
4 cil. en línea, TFSI
Potencia
150 hp / 5,000- 6,000 rpm
200 hp / 4,400-6,000 rpm
Torque
250 Nm / 1,500 -3,500 rpm
320 Nm/1,500 - 4,400 rpm
Tracción
delantera
delantera
Transmisión
S tronic 7 Vel.
S tronic 6 Vel.
Velocidad máxima
222 km/ hr
235km/hr
Aceleración 0-100 km/hr
7.7 s
6.5 s
Rendimiento de combustible (ciudad / carretera / combinado)
14.8/ 20.6/ 16.9  km/l
13.7/ 19.4/ 15.8  km/l
Norma de emisión de gases
EU6
EU6
Emisiones de CO₂ (ciudad / carretera / combinado)
159.1/ 114.0/ 138.8 gCO₂/km
171.2/ 121.2/ 148.7 gCO₂/km
       Dimensiones
Largo
4029 mm
4029 mm
Ancho
1740 mm
1740 mm
Alto
1433 mm
1433 mm
Distancia entre ejes
2563 mm
2563 mm
Peso en vacío (con conductor)
1,240 kg
1,335 kg
Capacidad del maletero
335 l
335 l
Capacidad del tanque de combustible
40 l
40 l
Número de puertas
5
5
       Sistemas de Asistencia y Seguridad
Airbags delanteros con interruptor para desconectar el airbag del acompañante
S
S
Airbags laterales delanteros con airbag de cabeza
S
S
Alarma antirrobo
S
S
Anclaje de fijación para asientos de niños para asientos traseros exteriores
S
S
Asistente de arranque en pendientes (Audi Hold Assist)
S
S
Asistente de estacionamiento trasero (sensores traseros)
S
-
Asistente de estacionamiento plus (sensores delanteros y traseros)
O
S
Cámara de reversa
O
O
Audi Park Assist
O
O
Audi Drive Select
S
S
Birlos de seguridad
S
S
Triángulo de seguridad
S
S
Cruise control y limitador de velocidad
S
S
Dirección asistida electromecánica
S
S
Frenos delanteros de disco
S
S
Frenos traseros de disco
S
S
S
S
S
S
A1 SB 30 TFSI
Cool
S
S
S
S
S
149.2 / 105.1/ 129.4 gCO₂/km
1740 mm
1,200 kg
335 l
40 l
5
S
O
O
O
O
O
S
9.4 s
200 Nm / 2,000 - 3,500 rpm
delantera
1433mm
2563 mm
4029 mm
15.7/ 22.3/ 18.1 km/l
EU6
1.0 L  (999 cm3)
 3 cil. en línea, TFSI
116 hp / 5,000 -5,500 rpm
S tronic 7 Vel.
203 km/hr
A1

# Ahora con PDF Miner

In [33]:
# !pip install pdfminer.six
from pdfminer.high_level import extract_pages, extract_text
text = extract_text("4. SampleAudi.pdf")
print(text)

A1

Ficha técnica

A1 Sportback 2024

        Motorización

A1 SB 30 TFSI
Cool

A1 SB 35 TFSI
Ego

A1 SB 40 TFSI
S line

Cilindrada

Motor

Potencia

Torque

Tracción

Transmisión

Velocidad máxima

Aceleración 0-100 km/hr

1.0 L  (999 cm3)

1.5 L (1,498 cm3)

2.0 L  (1,984 cm3)

 3 cil. en línea, TFSI

4 cil. en línea, TFSI

4 cil. en línea, TFSI

116 hp / 5,000 -5,500 rpm

150 hp / 5,000- 6,000 rpm

200 hp / 4,400-6,000 rpm

200 Nm / 2,000 - 3,500 rpm

250 Nm / 1,500 -3,500 rpm

320 Nm/1,500 - 4,400 rpm

delantera

S tronic 7 Vel.

203 km/hr

9.4 s

delantera

S tronic 7 Vel.

222 km/ hr

7.7 s

delantera

S tronic 6 Vel.

235km/hr

6.5 s

Rendimiento de combustible (ciudad / carretera / combinado)

15.7/ 22.3/ 18.1 km/l

14.8/ 20.6/ 16.9  km/l

13.7/ 19.4/ 15.8  km/l

Norma de emisión de gases

EU6

EU6

EU6

Emisiones de CO₂ (ciudad / carretera / combinado)

149.2 / 105.1/ 129.4 gCO₂/km

159.1/ 114.0/ 138.8 gCO₂/km

171.2/ 121.2/ 148.7 gCO₂/km

       Dimensiones

Largo

Ancho

Alto

Distancia entre ejes

Peso en vacío (con conductor)

Capacidad del maletero

Capacidad del tanque de combustible

Número de puertas

       Sistemas de Asistencia y Seguridad

Airbags delanteros con interruptor para desconectar el airbag del acompañante

Airbags laterales delanteros con airbag de cabeza

Alarma antirrobo

Anclaje de fijación para asientos de niños para asientos traseros exteriores

Asistente de arranque en pendientes (Audi Hold Assist)

Asistente de estacionamiento trasero (sensores traseros)

Asistente de estacionamiento plus (sensores delanteros y traseros)

Cámara de reversa

Audi Park Assist

Audi Drive Select

Birlos de seguridad

Triángulo de seguridad

Cruise control y limitador de velocidad

Dirección asistida electromecánica

Frenos delanteros de disco

Frenos traseros de disco

4029 mm

1740 mm

1433mm

2563 mm

1,200 kg

335 l

40 l

5

S

S

S

S

S

O

O

O

O

O

S

S

S

S

S

S

4029 mm

1740 mm

1433 mm

2563 mm

1,240 kg

335 l

40 l

5

S

S

S

S

S

S

O

O

O

S

S

S

S

S

S

S

4029 mm

1740 mm

1433 mm

2563 mm

1,335 kg

335 l

40 l

5

S

S

S

S

S

-

S

O

O

S

S

S

S

S

S

S

Indicador de presión de neumáticos

Llanta de refacción de tamaño reducido

Programa electrónico de estabilización (ESP)

Regulación de alcance de las luces automática, dinámica

Sensor de Luz y lluvia

Sistema de control de tracción ASR

Sistema de frenos antibloqueo ABS

Sistema start / stop con recuperación de energía

       Infotainment

Audi connect: Infotainment Services

Audi Smartphone interface

Audi music interface

Cuadro de instrumentos digital

Audi Virtual Cockpit

MMI Radio plus con pantalla táctil de 8.8"

MMI Navegación plus con pantalla táctil de 10.1"

Audi Sound System

SONOS 3D Premium Sound System

       Interiores y Confort

Apoyo lumbar  para los asientos delanteros

Asientos delanteros deportivos

Banca trasera de asientos con respaldo abatible 40/60

Cierre centralizado con control remoto

Climatizador manual

Climatizador automático confort

Descansabrazos central delantero

Elevacristales eléctricos con interruptor confort y limitador de fuerza

Iluminación interior LED

Llave confort "Keyless Entry"

Optica de aluminio en el interior

Paquete portaobjetos

Retrovisor interior antideslumbrante

Revestimiento interior del techo en tela negra

Tapizado de asientos en tela Novum

Tapizado de asientos en tela Derby

Volante multifuncional deportivo en piel de 3 brazos

Volante multifuncional plus deportivo en piel de 3 brazos con paletas de cambio

       Exterior

Carcasa de retrovisores exteriores en el color de la carrocería

Espejos exteriores con ajuste eléctrico

Faros LED

Luz de marcha diurna

Lavafaros

Limpia parabrisas trasero

Llantas de alta velocidad 195/55 R16 91V xl

Llantas de alta velocidad 215/45 R17 91W xl

Rines de aleación de aluminio en diseño dinámico de 10 radios de 16 pulgadas

Rines de aleación de aluminio en diseño estrella de 5 brazos de 17 pulgadas

       Paquete S line

Spoiler de techo "S line"

Inscripción S line en el exterior

Paquete exterior S line

Paquete interior decorativo S line

Pedales y apoyapiés en acero inoxidable

Rines de aleación de aluminio en diseño de 5 radios dobles de 17 pulgadas

Suspensión Deportiva S line

S

S

S

S

S

S

S

S

O

S

S

S

O

S

O

S

O

S

S

S

S

-

S

S

S

O

S

O

S

S

O

S

-

S

O

S

S

S

S

O

S

S

-

S

-

-

-

-

-

-

-

-

-

-

-

-

-

-

-

S

S

S

S

S

S

S

S

O

S

S

S

O

S

O

S

O

S

S

S

S

-

S

S

S

S

S

O

S

S

O

S

-

S

S

S

S

S

O

S

-

S

-

S

-

-

-

-

-

-

-

S

S

-

S

S

S

S

S

O

S

S

S

O

S

O

-

S

S

S

S

S

-

S

S

S

S

S

S

S

S

S

-

-

-

S

S

S

S

O

S

-

S

-

-

S

S

S

S

S

S

S

Tapizado de asientos en combinación alcántara/ piel sintéticas con grabado S
Line en el respaldo de los asientos delanteros

Volante multifuncional plus deportivo en piel de 3 brazos y palancas de cambio,
achatado en parte inferior

-

-

-

-

-

-

S

S

Esta ficha contiene información general disponible al momento de su emisión y solo se pretende sea usada como medio de referencia.

Verifique las características particulares del vehículo de su elección según la gama existente ofrecida por el distribuidor autorizado correspondiente.

Rines opcionales de mayor tamaño a los que se ofrecen en las versiones de serie pueden afectar negativamente los neumaticos y el manejo de confort al circular en malos caminos.

Los valores de rendimiento de combustible y CO2 se obtuvieron en condiciones controladas de laboratorio que no pueden ser reproducibles ni obtenerse en condiciones y hábitos de manejo convencional, debido a
situaciones climatológicas, combustible, topográficas y otros factores. Lo anterior, es dando cumplimiento a lo que establece la NOM-163-SEMARNAT-ENER.SCFI-2013 y  Ley para el Aprovechamiento Sustentable de la
Energía.

Los valores pueden cambiar dentro del rango mencionado de acuerdo a la versión y al equipamiento opcional seleccionado.

Este vehículo contiene los dispositivos de seguridad obligatorios de conformidad con la NOM-194-SE-2021

## Leer tablas desde un PDF con Tabula

In [2]:
#!pip install tabula-py[jpype]

from tabula import read_pdf
import pandas as pd

tablas = read_pdf(
    "4.1 sb2.pdf",
    pages="all",
    multiple_tables=False,
)

print(type(tablas))

<class 'list'>

### Parámetros
- pages='all': lee todas las páginas.
- multiple_tables=False: interpreta todo como una sola tabla.

In [4]:
df = tablas[0]
df.head(10)

,Edición,Fecha,Ganador,Marcador,Perdedor,Estadio,Ciudad
0,I,15 de\renero\rde 1967,Green Bay\rPackers,35 - 10,Kansas City\rChiefs,Los Angeles Memorial\rColiseum,"Los Ángeles, California"
1,II,14 de\renero\rde 1968,Green Bay\rPackers (2),33 - 14,Oakland Raiders,Miami Orange Bowl,"Miami, Florida"
2,III,12 de\renero\rde 1969,New York Jets,16 - 7,Baltimore Colts,Miami Orange Bowl (2),"Miami, Florida (2)"
3,IV,11 de\renero\rde 1970,Kansas City\rChiefs,23 - 7,Minnesota\rVikings,Tulane Stadium,"Nueva Orleans,\rLuisiana"
4,V,17 de\renero\rde 1971,Baltimore Colts,16 - 13,Dallas Cowboys,Miami Orange Bowl (3),"Miami, Florida (3)"
5,VI,16 de\renero\rde 1972,Dallas Cowboys,24 - 3,Miami Dolphins,Tulane Stadium (2),"Nueva Orleans,\rLuisiana (2)"
6,VII,14 de\renero\rde 1973,Miami Dolphins,14 - 7,Washington\rRedskins,Los Angeles Memorial\rColiseum (2),"Los Ángeles, California\r(2)"
7,VIII,13 de\renero\rde 1974,Miami Dolphins\r(2),24 - 7,Minnesota\rVikings (2),Rice Stadium,"Houston, Texas"
8,IX,12 de\renero\rde 1975,Pittsburgh\rSteelers,16 - 6,Minnesota\rVikings (3),Tulane Stadium (3),"Nueva Orleans,\rLuisiana (3)"
9,X,18 de\renero\rde 1976,Pittsburgh\rSteelers (2),21 - 17,Dallas Cowboys\r(2),Miami Orange Bowl (4),"Miami, Florida (4)"

## Limpieza de datos extraídos

In [12]:
df['Fecha'] = df['Fecha'].str.replace('\r', ' ') 
df['Ganador'] = df['Ganador'].str.replace('\r', ' ').str.rstrip('(0123456789)') 
df['Marcador'] = df['Marcador'].str.replace(r'\[.*\]', '', regex=True) 
df['Perdedor'] = df['Perdedor'].str.replace('\r', ' ').str.rstrip('(0123456789)') 
df['Estadio'] = df['Estadio'].str.replace('\r', ' ').str.rstrip('(0123456789)') 
df['Ciudad'] = df['Ciudad'].str.replace('\r', ' ').str.rstrip('(0123456789)')

Los PDFs suelen contener saltos de línea, referencias y caracteres especiales que deben limpiarse.

In [13]:
df.head(10)

,Edición,Fecha,Ganador,Marcador,Perdedor,Estadio,Ciudad
0,I,15 de enero de 1967,Green Bay Packers,35 - 10,Kansas City Chiefs,Los Angeles Memorial Coliseum,"Los Ángeles, California"
1,II,14 de enero de 1968,Green Bay Packers,33 - 14,Oakland Raiders,Miami Orange Bowl,"Miami, Florida"
2,III,12 de enero de 1969,New York Jets,16 - 7,Baltimore Colts,Miami Orange Bowl,"Miami, Florida"
3,IV,11 de enero de 1970,Kansas City Chiefs,23 - 7,Minnesota Vikings,Tulane Stadium,"Nueva Orleans, Luisiana"
4,V,17 de enero de 1971,Baltimore Colts,16 - 13,Dallas Cowboys,Miami Orange Bowl,"Miami, Florida"
5,VI,16 de enero de 1972,Dallas Cowboys,24 - 3,Miami Dolphins,Tulane Stadium,"Nueva Orleans, Luisiana"
6,VII,14 de enero de 1973,Miami Dolphins,14 - 7,Washington Redskins,Los Angeles Memorial Coliseum,"Los Ángeles, California"
7,VIII,13 de enero de 1974,Miami Dolphins,24 - 7,Minnesota Vikings,Rice Stadium,"Houston, Texas"
8,IX,12 de enero de 1975,Pittsburgh Steelers,16 - 6,Minnesota Vikings,Tulane Stadium,"Nueva Orleans, Luisiana"
9,X,18 de enero de 1976,Pittsburgh Steelers,21 - 17,Dallas Cowboys,Miami Orange Bowl,"Miami, Florida"

## Ejemplo práctico

In [14]:
datos = pd.DataFrame({
'Equipo':['Chiefs\r','Eagles\r'],
'Marcador':['35-31[1]','28-21[2]']
})

datos

     Equipo  Marcador
0  Chiefs\r  35-31[1]
1  Eagles\r  28-21[2]

In [16]:
datos['Equipo']=datos['Equipo'].str.replace('\r','', regex=False)
datos['Marcador']=datos['Marcador'].str.replace(r'\\[.*\\]','', regex=True)
datos

   Equipo  Marcador
0  Chiefs  35-31[1]
1  Eagles  28-21[2]

## Buenas prácticas
1. Revisar nulos.
2. Revisar tipos de datos.
3. Limpiar caracteres especiales.
4. Convertir fechas y números.

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Edición   62 non-null     object
 1   Fecha     62 non-null     object
 2   Ganador   59 non-null     object
 3   Marcador  59 non-null     object
 4   Perdedor  59 non-null     object
 5   Estadio   62 non-null     object
 6   Ciudad    62 non-null     object
dtypes: object(7)
memory usage: 3.5+ KB

In [18]:
df.isna().sum()

Edición     0
Fecha       0
Ganador     3
Marcador    3
Perdedor    3
Estadio     0
Ciudad      0
dtype: int64

## Resumen para examen
- tabula.read_pdf()
- pages='all'
- multiple_tables
- DataFrame
- str.replace()
- regex