In [ ]:

import pandas as pd
excel_empleados = pd.read_excel('records.xls', sheet_name='Empleados')
excel_autos = pd.read_excel('records.xls', sheet_name='Autos')

In [ ]:
excel_empleados

   EmplID EmplName EmpRole
0       1     John     CEO
1       2     Anna  Editor
2       3    Karen  Author

In [ ]:
excel_autos

        Marca subMarca  Modelo  kilometraje  precio MXP
0       Honda    Civic    2015        67000      256000
1  VolksWagen    Jetta    2009       148500      110000
2     Toyota    Sienna    2011       140500      149900

In [ ]:
new_row = pd.Series(["Honda", "Fit", 2015, 110000, 140000],   index = ["Marca", "subMarca", "Modelo", "kilometraje",   "precio MXP"])

In [ ]:
row_df = pd.DataFrame([new_row])

In [ ]:
excel_autos = pd.concat([ excel_autos, row_df], ignore_index=True)

In [ ]:

new_row1 = pd.Series(["Mazda", "CX-5", 2017, 65000, 265000])
new_row2 = pd.Series(["Susuki", "Vitara", 2016, 85000, 185000])
new_row3 = pd.Series(["Audi", "A4", 2010, 185000, 225000])

new_rows_df = pd.concat([new_row1,new_row2,new_row3],axis=1)
new_rows_df

        0       1       2
0   Mazda  Susuki    Audi
1    CX-5  Vitara      A4
2    2017    2016    2010
3   65000   85000  185000
4  265000  185000  225000

In [ ]:
new_rows_df=new_rows_df.T

In [ ]:
new_rows_df

        0       1     2       3       4
0   Mazda    CX-5  2017   65000  265000
1  Susuki  Vitara  2016   85000  185000
2    Audi      A4  2010  185000  225000

In [ ]:
new_rows_df.columns = ["Marca", "subMarca", "Modelo", "kilometraje", "precio MXP"]
new_rows_df

    Marca subMarca Modelo kilometraje precio MXP
0   Mazda     CX-5   2017       65000     265000
1  Susuki   Vitara   2016       85000     185000
2    Audi       A4   2010      185000     225000

In [ ]:
new_rows_df.reset_index(drop=True)

    Marca subMarca Modelo kilometraje precio MXP
0   Mazda     CX-5   2017       65000     265000
1  Susuki   Vitara   2016       85000     185000
2    Audi       A4   2010      185000     225000

In [ ]:
excel_autos = pd.concat([excel_autos,new_rows_df], ignore_index=True)

In [ ]:
excel_autos

        Marca subMarca Modelo kilometraje precio MXP
0       Honda    Civic   2015       67000     256000
1  VolksWagen    Jetta   2009      148500     110000
2     Toyota    Sienna   2011      140500     149900
3       Honda      Fit   2015      110000     140000
4       Mazda     CX-5   2017       65000     265000
5      Susuki   Vitara   2016       85000     185000
6        Audi       A4   2010      185000     225000

In [ ]:
excel_autos.loc[excel_autos["Marca"]=="Honda"]

   Marca subMarca Modelo kilometraje precio MXP
0  Honda    Civic   2015       67000     256000
3  Honda      Fit   2015      110000     140000

In [ ]:
excel_autos.loc[excel_autos["Marca"]=="Honda"].loc[:,["subMarca", "Modelo"]]

  subMarca Modelo
0    Civic   2015
3      Fit   2015

In [ ]:
excel_autos[["subMarca", "Modelo"]]

  subMarca Modelo
0    Civic   2015
1    Jetta   2009
2   Sienna   2011
3      Fit   2015
4     CX-5   2017
5   Vitara   2016
6       A4   2010

In [ ]:
excel_autos.loc[ (excel_autos["Marca"]=="Honda") &
   (excel_autos["kilometraje"] < 100000 ) ]

   Marca subMarca Modelo kilometraje precio MXP
0  Honda    Civic   2015       67000     256000

In [ ]:
excel_autos.at[6,"kilometraje"] = 195000

#excel_autos.update(pd.DataFrame([[6]["kilometraje"],[195000]]))
#pd.DataFrame([["Emil"], [17]])

In [ ]:
excel_autos

        Marca subMarca Modelo kilometraje precio MXP
0       Honda    Civic   2015       67000     256000
1  VolksWagen    Jetta   2009      148500     110000
2     Toyota    Sienna   2011      140500     149900
3       Honda      Fit   2015      110000     140000
4       Mazda     CX-5   2017       65000     265000
5      Susuki   Vitara   2016       85000     185000
6        Audi       A4   2010      195000     225000

In [ ]:

excel_autos.loc[(excel_autos["Marca"]== "Audi")&(excel_autos["subMarca"]=="A4"),"kilometraje"] = 200000

In [ ]:
excel_autos

        Marca subMarca Modelo kilometraje precio MXP
0       Honda    Civic   2015       67000     256000
1  VolksWagen    Jetta   2009      148500     110000
2     Toyota    Sienna   2011      140500     149900
3       Honda      Fit   2015      110000     140000
4       Mazda     CX-5   2017       65000     265000
5      Susuki   Vitara   2016       85000     185000
6        Audi       A4   2010      200000     225000

In [ ]:
excel_autos.drop(2).reset_index(drop=True)

        Marca subMarca Modelo kilometraje precio MXP
0       Honda    Civic   2015       67000     256000
1  VolksWagen    Jetta   2009      148500     110000
2       Honda      Fit   2015      110000     140000
3       Mazda     CX-5   2017       65000     265000
4      Susuki   Vitara   2016       85000     185000
5        Audi       A4   2010      200000     225000

In [ ]:
excel_autos2 = excel_autos.loc[excel_autos["precio MXP"] <= 200000]
excel_autos2

        Marca subMarca Modelo kilometraje precio MXP
1  VolksWagen    Jetta   2009      148500     110000
2     Toyota    Sienna   2011      140500     149900
3       Honda      Fit   2015      110000     140000
5      Susuki   Vitara   2016       85000     185000

<br><br><br><br><br>
<h1>pandasql</h1>
<br><br><br><br><br>

In [109]:
!pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from pandasql) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.11/dist-packages (from pandasql) (2.0.40)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy->pandasql) (3.2.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy->pandasql) (4.13.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26773 sha256=f9509f6ebdc45fb8d1d10cb96ff9bf308216ba964b213b09e4d7f32c31c3021e
  Stored in directory: /root/.cache/pip/wheels/68/5d/a5/edc271b998f909801d7956959f699b976cc9896075dc47c153
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [110]:

from pandasql import sqldf

In [122]:
excel_autos

        Marca subMarca Modelo kilometraje precio MXP
0       Honda    Civic   2015       67000     256000
1  VolksWagen    Jetta   2009      148500     110000
2     Toyota    Sienna   2011      140500     149900
3       Honda      Fit   2015      110000     140000
4       Mazda     CX-5   2017       65000     265000
5      Susuki   Vitara   2016       85000     185000
6        Audi       A4   2010      200000     225000

In [123]:
rdf = sqldf("SELECT * FROM excel_autos;")
rdf

        Marca subMarca  Modelo  kilometraje  precio MXP
0       Honda    Civic    2015        67000      256000
1  VolksWagen    Jetta    2009       148500      110000
2     Toyota    Sienna    2011       140500      149900
3       Honda      Fit    2015       110000      140000
4       Mazda     CX-5    2017        65000      265000
5      Susuki   Vitara    2016        85000      185000
6        Audi       A4    2010       200000      225000

In [129]:
query = 'SELECT * FROM excel_autos WHERE Marca = "Honda";'
rdf = sqldf(query)
rdf

   Marca subMarca  Modelo  kilometraje  precio MXP
0  Honda    Civic    2015        67000      256000
1  Honda      Fit    2015       110000      140000

In [130]:
query = 'SELECT subMarca, Modelo FROM excel_autos WHERE Marca = "Honda";'
rdf = sqldf(query)
rdf

  subMarca  Modelo
0    Civic    2015
1      Fit    2015

In [131]:
query = 'SELECT subMarca, Modelo FROM excel_autos;'
rdf = sqldf(query)
rdf

  subMarca  Modelo
0    Civic    2015
1    Jetta    2009
2   Sienna    2011
3      Fit    2015
4     CX-5    2017
5   Vitara    2016
6       A4    2010

In [132]:
query = 'SELECT * FROM excel_autos WHERE marca = "Honda" and kilometraje < 100000;'
rdf = sqldf(query)
rdf

   Marca subMarca  Modelo  kilometraje  precio MXP
0  Honda    Civic    2015        67000      256000