In [1]:
import pandas as pd
import pandas as pd

In [2]:
df1 = pd.read_csv("data1.csv")
print(df1.head())
df2 = pd.read_csv("data2.csv")
print(df2.head())
df3 = pd.read_csv("data3.csv")
print(df3.head())
df4 = pd.read_csv("data4.csv")
print(df4.head())

  Employee_ID Gender   Age  Education_Level Relationship_Status     Hometown  \
0   EID_23371      F  42.0                4             Married     Franklin
1   EID_18000      M  24.0                3              Single  Springfield
2    EID_3891      F  58.0                3             Married      Clinton
3   EID_17492      F  26.0                3              Single      Lebanon
4   EID_22534      F  31.0                1             Married  Springfield

                        Unit Decision_skill_possess  Time_of_service  \
0                         IT             Conceptual              4.0
1                  Logistics             Analytical              5.0
2                    Quality             Conceptual             27.0
3  Human Resource Management             Behavioral              4.0
4                  Logistics             Conceptual              5.0

   Time_since_promotion  ...  Compensation_and_Benefits  Work_Life_balance  \
0                     4  ...                      type2                3.0
1                     4  ...                      type2                4.0
2                     3  ...                      type2                1.0
3                     3  ...                      type2                1.0
4                     4  ...                      type3                3.0

   VAR1    VAR2    VAR3  VAR4  VAR5  VAR6  VAR7  Attrition_rate
0     4  0.7516  1.8688   2.0     4     5     3          0.1841
1     3 -0.9612 -0.4537   2.0     3     5     3          0.0670
2     4 -0.9612 -0.4537   3.0     3     8     3          0.0851
3     3 -1.8176 -0.4537   NaN     3     7     3          0.0668
4     1  0.7516 -0.4537   2.0     2     8     2          0.1827

[5 rows x 24 columns]
  Employee_ID Gender   Age  Education_Level Relationship_Status     Hometown  \
0   EID_22713      F  32.0                5              Single  Springfield
1    EID_9658      M  65.0                2              Single      Lebanon
2   EID_22203      M  52.0                3             Married  Springfield
3    EID_7652      M  50.0                5              Single   Washington
4    EID_6516      F  44.0                3             Married     Franklin

        Unit Decision_skill_possess  Time_of_service  Time_since_promotion  \
0        R&D             Conceptual              7.0                     4
1         IT              Directive             41.0                     2
2      Sales              Directive             21.0                     3
3  Marketing             Analytical             11.0                     4
4        R&D             Conceptual             12.0                     4

   ...  Pay_Scale  Compensation_and_Benefits  Work_Life_balance  VAR1    VAR2  \
0  ...        4.0                      type2                1.0     3 -0.9612
1  ...        1.0                      type2                1.0     4 -0.9612
2  ...        8.0                      type3                1.0     4 -0.1048
3  ...        2.0                      type0                4.0     3 -0.1048
4  ...        2.0                      type2                4.0     4  1.6081

     VAR3  VAR4  VAR5  VAR6  VAR7
0 -0.4537   2.0     1     8     4
1  0.7075   1.0     2     8     2
2  0.7075   2.0     1     9     3
3  0.7075   2.0     2     8     3
4  0.7075   2.0     2     7     4

[5 rows x 23 columns]
  Employee_ID  Computer_OS  Computer_OS_version   Computer_tickets  Mobile_OS  \
0   EID_18343      Windows                    8                  1    Android
1    EID_4861      Windows                    7                  2    Android
2   EID_16936      Windows                   10                  3    Android
3   EID_16384      Windows                   10                  1    Android
4   EID_10666      Windows                    7                  7    Android

    Mobile_OS_version   Mobile_tickets
0                 9.0                0
1                 8.0                0
2                10.0                0
3                 7.0                1
4                10.0                4
  Employee_ID  Computer_OS  Computer_OS_version   Computer_tickets  Mobile_OS  \
0   EID_19108      Windows                   10                  2    Android
1   EID_13997      Windows                   10                 12    Android
2   EID_10789        MacOS             Catalina                  0        iOS
3    EID_1833      Windows                   10                  9    Android
4    EID_8825      Windows                    8                  3    Android

    Mobile_OS_version   Mobile_tickets
0                 8.0                0
1                10.0                1
2                12.0                0
3                 7.0                0
4                 9.0                2

In [3]:
datosUsuarios = pd.concat([df1, df2], ignore_index=True)

datosSO = pd.concat([df3, df4], ignore_index=True)

todo = pd.merge(datosUsuarios, datosSO, on='Employee_ID', how='outer')

print(todo.head())

  Employee_ID Gender   Age  Education_Level Relationship_Status     Hometown  \
0   EID_10000      M  37.0                3             Married  Springfield
1   EID_10001      F  46.0                2              Single      Lebanon
2   EID_10003      F  37.0                4              Single   Washington
3   EID_10004      M  46.0                3             Married  Springfield
4   EID_10006      M  37.0                3             Married     Franklin

                        Unit Decision_skill_possess  Time_of_service  \
0  Human Resource Management             Analytical             14.0
1                 Operarions             Conceptual             20.0
2                  Logistics             Analytical             10.0
3                 Purchasing             Analytical             22.0
4                      Sales             Conceptual              9.0

   Time_since_promotion  ...  VAR5  VAR6  VAR7  Attrition_rate  Computer_OS  \
0                     4  ...     1     5     3             NaN        MacOS
1                     3  ...     4     5     4          0.0263      Windows
2                     2  ...     2     7     4          0.0124      Windows
3                     1  ...     3     6     3             NaN      Windows
4                     2  ...     2     8     3          0.0312          NaN

    Computer_OS_version   Computer_tickets   Mobile_OS   Mobile_OS_version  \
0              Catalina                  2         iOS                13.0
1                     8                  8     Android                 7.0
2                     7                  1     Android                10.0
3                    10                  1     Android                10.0
4                   NaN                  3     Android                 7.0

    Mobile_tickets
0                0
1                1
2                1
3                1
4                0

[5 rows x 30 columns]

In [4]:
todo[' Computer_OS'] = todo[' Computer_OS'].fillna("No registrado")
todo[' Mobile_OS'] = todo[' Mobile_OS'].fillna("No registrado")
todo[' Computer_OS_version'] = todo[' Computer_OS_version'].fillna("No registrado")
todo[' Mobile_OS_version'] = todo[' Mobile_OS_version'].fillna("No registrado")
print(todo.head(30))

   Employee_ID Gender   Age  Education_Level Relationship_Status     Hometown  \
0    EID_10000      M  37.0                3             Married  Springfield
1    EID_10001      F  46.0                2              Single      Lebanon
2    EID_10003      F  37.0                4              Single   Washington
3    EID_10004      M  46.0                3             Married  Springfield
4    EID_10006      M  37.0                3             Married     Franklin
5    EID_10008      M  41.0                4             Married     Franklin
6    EID_10009      M  37.0                3             Married     Franklin
7    EID_10010      F  46.0                3             Married   Washington
8    EID_10011      F  41.0                4              Single     Franklin
9    EID_10018      F  37.0                4              Single      Lebanon
10   EID_10020      M  41.0                3             Married   Washington
11   EID_10025      F   NaN                3              Single      Clinton
12   EID_10026      F  41.0                3             Married     Franklin
13   EID_10027      F  37.0                5              Single      Lebanon
14   EID_10029      M  41.0                3             Married      Lebanon
15   EID_10030      M  37.0                3             Married     Franklin
16   EID_10031      M  46.0                2             Married  Springfield
17   EID_10033      F  37.0                1              Single   Washington
18   EID_10035      F  41.0                4             Married      Lebanon
19   EID_10042      F  36.0                4             Married      Lebanon
20   EID_10043      F  44.0                3             Married      Clinton
21   EID_10044      F  40.0                3             Married      Lebanon
22   EID_10045      M   NaN                3             Married     Franklin
23   EID_10049      F  45.0                4             Married  Springfield
24   EID_10050      M  40.0                3              Single      Lebanon
25   EID_10054      F  36.0                1             Married  Springfield
26   EID_10056      F  40.0                2              Single  Springfield
27   EID_10058      F  45.0                2             Married   Washington
28   EID_10059      F  40.0                3             Married      Clinton
29    EID_1006      F  53.0                4             Married  Springfield

                         Unit Decision_skill_possess  Time_of_service  \
0   Human Resource Management             Analytical             14.0
1                  Operarions             Conceptual             20.0
2                   Logistics             Analytical             10.0
3                  Purchasing             Analytical             22.0
4                       Sales             Conceptual              9.0
5                  Operarions             Analytical             18.0
6                       Sales             Behavioral             13.0
7                          IT             Behavioral             22.0
8                     Quality              Directive             13.0
9                       Sales              Directive             15.0
10                      Sales             Behavioral             10.0
11                    Quality              Directive             22.0
12                    Quality             Analytical             18.0
13                  Marketing             Analytical             11.0
14     Accounting and Finance             Behavioral              8.0
15                   Security             Conceptual             10.0
16                 Operarions             Behavioral             16.0
17                  Marketing              Directive             11.0
18                         IT             Conceptual             10.0
19                 Production             Behavioral              9.0
20                   Security             Conceptual             21.0
21                         IT             Analytical             13.0
22                  Marketing             Behavioral             10.0
23                         IT             Conceptual              7.0
24     Accounting and Finance             Analytical             16.0
25                 Operarions              Directive              8.0
26                      Sales             Conceptual             16.0
27                         IT              Directive             14.0
28                         IT             Analytical             15.0
29                   Security             Analytical             23.0

    Time_since_promotion  ...  VAR5  VAR6  VAR7  Attrition_rate  \
0                      4  ...     1     5     3             NaN
1                      3  ...     4     5     4          0.0263
2                      2  ...     2     7     4          0.0124
3                      1  ...     3     6     3             NaN
4                      2  ...     2     8     3          0.0312
5                      2  ...     4     5     3          0.0163
6                      4  ...     2     8     3          0.1973
7                      3  ...     5     6     3          0.2831
8                      3  ...     3     7     3          0.1783
9                      4  ...     3     7     3          0.1090
10                     2  ...     3     7     4             NaN
11                     3  ...     3     8     2          0.1742
12                     1  ...     4     8     3             NaN
13                     3  ...     2     9     4             NaN
14                     3  ...     2     7     5          0.0984
15                     4  ...     3     8     1             NaN
16                     2  ...     1     9     4             NaN
17                     4  ...     2     8     1             NaN
18                     4  ...     3     8     1             NaN
19                     4  ...     3     8     2             NaN
20                     3  ...     2     6     3          0.1840
21                     4  ...     2     6     3          0.1996
22                     3  ...     2     7     4          0.0312
23                     3  ...     2     6     3          0.1287
24                     4  ...     3     6     3          0.1623
25                     4  ...     5     8     3          0.2145
26                     1  ...     2     9     3          0.0409
27                     4  ...     3     9     3          0.0902
28                     1  ...     1     8     1             NaN
29                     2  ...     2     7     3             NaN

      Computer_OS   Computer_OS_version   Computer_tickets      Mobile_OS  \
0           MacOS              Catalina                  2            iOS
1         Windows                     8                  8        Android
2         Windows                     7                  1        Android
3         Windows                    10                  1        Android
4   No registrado         No registrado                  3        Android
5           MacOS              Catalina                  0            iOS
6         Windows                    10                  1        Android
7   No registrado         No registrado                  3        Android
8         Windows                     7                  3        Android
9         Windows                     8                  3        Android
10          Linux                ubuntu                  2            iOS
11        Windows                    10                  3        Android
12        Windows                    10                  1            iOS
13        Windows                     8                  0        Android
14        Windows                    10                  3        Android
15        Windows                     7                  2        Android
16        Windows                     8                  4  No registrado
17        Windows                     8                  3            iOS
18        Windows                    10                  1            iOS
19        Windows                     8                  1        Android
20        Windows                     7                  1        Android
21          MacOS         No registrado                  3        Android
22        Windows                    10                  9        Android
23        Windows                     7                  1        Android
24        Windows                    10                  5        Android
25        Windows                    10                  3        Android
26        Windows                    10                  2        Android
27        Windows                    10                  8        Android
28        Windows                     7                  6        Android
29        Windows                     8                  1        Android

     Mobile_OS_version   Mobile_tickets
0                 13.0                0
1                  7.0                1
2                 10.0                1
3                 10.0                1
4                  7.0                0
5                 12.0                0
6                  7.0                1
7                  8.0                2
8                  7.0                0
9                  8.0                0
10                12.0                0
11                 9.0                0
12                11.0                1
13                 7.0                0
14                 8.0                0
15                10.0                0
16       No registrado                2
17                12.0                3
18                12.0                0
19                 8.0                0
20                10.0                0
21                 8.0                0
22                 7.0                0
23                 8.0                0
24                 9.0                0
25                 7.0                1
26                10.0                1
27                 9.0                1
28                 9.0                2
29                 8.0                0

[30 rows x 30 columns]

Consulta 1. Por cada lugar ("Hometown"), cuántos hombres y cuántas mujeres hay.

In [5]:
lugarFyM = pd.pivot_table(
    todo,
    index="Hometown",
    columns="Gender",
    aggfunc="size",
)
lugarFyM.head()

Gender          F     M
Hometown
Clinton       489   323
Franklin     1231   950
Lebanon      1695  1258
Springfield  1470  1014
Washington    957   613

Consulta 2: El número de empleados que utilizan cada Sistema Operativo de Escritorio

In [6]:
SOescritorio = pd.pivot_table(
    todo,
    index=" Computer_OS",
    values="Employee_ID",
    aggfunc="count"
)

SOescritorio.head()

               Employee_ID
 Computer_OS
Linux                  480
MacOS                 1634
No registrado          158
Windows               7728

Consulta 3: El promedio de la edad y de nivel de educación de las personas por cada Sistema Operativo en su dispositivo móvil.

In [7]:
EdadNivEdProm = todo.groupby([' Mobile_OS'])[['Age','Education_Level']].mean()
EdadNivEdProm.head()

                     Age  Education_Level
 Mobile_OS
Android        39.512002         3.204988
No registrado  40.974265         3.146341
iOS            40.099076         3.185979

Consulta 4: El número total de tickets generados por las personas que usan cada uno de los sistemas operativos de escritorio. Como columnas, en un nivel superior agrupa por género, y en un nivel inferior por estado civil.

In [8]:
tickOS = pd.pivot_table(
    todo,
    index=' Computer_OS',
    columns=['Gender', 'Relationship_Status'],
    values='Employee_ID',
    aggfunc='count',
)

tickOS.head()

Gender                    F              M
Relationship_Status Married Single Married Single
 Computer_OS
Linux                   183     91     135     71
MacOS                   601    359     438    236
No registrado            54     34      51     19
Windows                2931   1589    2068   1140

Consulta 5: Genera un DataFrame que contenga como filas, cada uno de los lugares en la columna "Hometown", y como columnas de primer nivel el estado relacional, y como segundo nivel el género. Los valores a mostrar en cada intersección de fila con columna deben ser el promedio de la columna "Attrition_rate" que cumplan con esos valores de fila y columna.

In [9]:
df5 = pd.pivot_table(
    todo,
    index='Hometown',
    columns=['Relationship_Status','Gender'],
    values="Attrition_rate",
    aggfunc="mean"
)
df5.head()

Relationship_Status   Married              Single
Gender                      F         M         F         M
Hometown
Clinton              0.177888  0.198820  0.204844  0.176654
Franklin             0.183555  0.191947  0.189822  0.188758
Lebanon              0.172859  0.188820  0.189632  0.212963
Springfield          0.187812  0.208490  0.189354  0.190528
Washington           0.192603  0.193686  0.180227  0.183278

Enviar el resultado de cada solicitud de información a un mismo archivo XLS[X], donde el resultado de cada consulta debe ir en su propia hoja de trabajo. Cada hoja de trabajo debe llevar por nombre c1, c2, c3, c4 y c5, cada una correspondiente a cada una de las 5 consultas planteadas.

In [10]:
with pd.ExcelWriter('consultas.xlsx') as writer:
    lugarFyM.to_excel(writer, sheet_name='c1')
    SOescritorio.to_excel(writer, sheet_name='c2')
    EdadNivEdProm.to_excel(writer, sheet_name='c3')
    tickOS.to_excel(writer, sheet_name='c4')
    df5.to_excel(writer, sheet_name='c5')